spring.application.name=pokemon-manager

pokemonapi.base.url=${POKEMON_URL:https://pokeapi.co/api/v2}

# Configuração do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/pokemon
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true

# Configuração redis
spring.data.redis.host=localhost
spring.data.redis.port=6379